---
- name: Yum - add Icinga repository (stable)
  become: yes
  yum_repository:
    file: /etc/yum.repos.d/ICINGA-release
    name: icinga-stable-release
    description: ICINGA (stable release for epel)
    baseurl: "{{ icinga_repo_yum_stable_url }}"
    gpgkey: "{{ icinga_repo_yum_stable_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_stable }}"
- name: Yum - add Icinga repository (testing)
  become: yes
  yum_repository:
    file: /etc/yum.repos.d/ICINGA-testing
    name: icinga-testing-builds
    description: ICINGA (testing builds for epel)
    baseurl: "{{ icinga_repo_yum_testing_url }}"
    gpgkey: "{{ icinga_repo_yum_testing_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_testing }}"
- name: Yum - add Icinga repository (snapshot)
  become: yes
  yum_repository:
    file: /etc/yum.repos.d/ICINGA-snapshot
    name: icinga-snapshot-builds
    description: ICINGA (snapshot builds for epel)
    baseurl: "{{ icinga_repo_yum_snapshot_url }}"
    gpgkey: "{{ icinga_repo_yum_snapshot_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_snapshot }}"
- name: Yum - add EPEL repository
  become: yes
  yum:
    name: epel-release
    state: "{{ 'present' if icinga_repo_epel else 'absent' }}"
- name: Yum - add SCL repositories
  become: yes
  yum:
    name: centos-release-scl
    state: "{{ 'present' if icinga_repo_scl else 'absent' }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version < "8"
